<?xml version="1.0" encoding="utf-8"?>
<robot name="my_bot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find mybot_description)/urdf/materials.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/my_bot.gazebo" />
    <xacro:include filename="$(find mybot_description)/urdf/wheel_macro.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/hand_macro.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/eye_macro.xacro" />
    <xacro:include filename="$(find mybot_description)/urdf/transmission.xacro" />

    <xacro:property name="base_side" value="0.6"/>
    <xacro:property name="arm_pos" value="${base_side*2/3}"/>

    <xacro:property name="wheel_rad" value="0.125"/>
    <xacro:property name="wheel_len" value="0.08"/>

    <xacro:property name="shoulder_l" value="0.025"/>
    <xacro:property name="shoulder_w" value="0.02"/>
    <xacro:property name="shoulder_h" value="0.05"/>

    <xacro:property name="shoulder_forward_l" value="0.05"/>
    <xacro:property name="shoulder_forward_w" value="0.07"/>
    <xacro:property name="shoulder_forward_h" value="0.05"/>

    <xacro:property name="upper_arm_rad" value="0.03"/>
    <xacro:property name="upper_arm_len" value="0.4"/>
    
    <xacro:property name="arm_center_l" value="0.06"/>
    <xacro:property name="arm_center_w" value="0.08"/>
    <xacro:property name="arm_center_h" value="0.01"/>
    
    <xacro:property name="hand_l" value="0.11"/>
    <xacro:property name="hand_w" value="0.01"/>
    <xacro:property name="hand_h" value="0.15"/>

    <xacro:property name="ocular_rad" value="0.08"/>
    <xacro:property name="ocular_len" value="0.2"/>
    
    <xacro:property name="neck_rad" value="0.05"/>
    <xacro:property name="neck_len" value="0.2"/>
      
    <!-- * * * Link Definitions * * * -->

    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${base_side/2}" rpy="0 0 0"/>
            <geometry>
                <box size="${base_side} ${base_side} ${base_side}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size="${base_side} ${base_side} ${base_side}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="2"/>
            <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
        </inertial>
    </link>
    
    <xacro:link_wheel name="wheel_1_left" wheel_rad="${wheel_rad}" wheel_len="${wheel_len}" />
    <xacro:link_wheel_line name="wheel_1_left_line" wheel_rad="${wheel_rad}" />
    
    <xacro:link_wheel name="wheel_2_left" wheel_rad="${wheel_rad}" wheel_len="${wheel_len}" />
    <xacro:link_wheel_line name="wheel_2_left_line" wheel_rad="${wheel_rad}" />
    
    <xacro:link_wheel name="wheel_3_left" wheel_rad="${wheel_rad}" wheel_len="${wheel_len}" />
    <xacro:link_wheel_line name="wheel_3_left_line" wheel_rad="${wheel_rad}" />
    
    <xacro:link_wheel name="wheel_1_right" wheel_rad="${wheel_rad}" wheel_len="${wheel_len}" />
    <xacro:link_wheel_line name="wheel_1_right_line" wheel_rad="${wheel_rad}" />
    
    <xacro:link_wheel name="wheel_2_right" wheel_rad="${wheel_rad}" wheel_len="${wheel_len}" />
    <xacro:link_wheel_line name="wheel_2_right_line" wheel_rad="${wheel_rad}" />
    
    <xacro:link_wheel name="wheel_3_right" wheel_rad="${wheel_rad}" wheel_len="${wheel_len}" />
    <xacro:link_wheel_line name="wheel_3_right_line" wheel_rad="${wheel_rad}" />

    <xacro:link_shoulder name="left_shoulder_link" shoulder_l="${shoulder_l}" shoulder_w="${shoulder_w}" shoulder_h="${shoulder_h}" />
    <xacro:link_shoulder_forward name="left_shoulder_forward_link" shoulder_forward_l="${shoulder_forward_l}" shoulder_forward_w="${shoulder_forward_w}" shoulder_forward_h="${shoulder_forward_h}" />
    <xacro:link_upper_arm name="left_upper_arm_link" upper_arm_rad="${upper_arm_rad}" upper_arm_len="${upper_arm_len}" />
    <xacro:link_arm_center name="left_center_link" arm_center_l="${arm_center_l}" arm_center_w="${arm_center_w}" arm_center_h="${arm_center_h}" />
    <xacro:link_hand name="left_hand_link" hand_l="${hand_l}" hand_w="${hand_w}" hand_h="${hand_h}" />
    
    <xacro:link_shoulder name="right_shoulder_link" shoulder_l="${shoulder_l}" shoulder_w="${shoulder_w}" shoulder_h="${shoulder_h}" />
    <xacro:link_shoulder_forward name="right_shoulder_forward_link" shoulder_forward_l="${shoulder_forward_l}" shoulder_forward_w="${shoulder_forward_w}" shoulder_forward_h="${shoulder_forward_h}" />
    <xacro:link_upper_arm name="right_upper_arm_link" upper_arm_rad="${upper_arm_rad}" upper_arm_len="${upper_arm_len}" />
    <xacro:link_arm_center name="right_center_link" arm_center_l="${arm_center_l}" arm_center_w="${arm_center_w}" arm_center_h="${arm_center_h}" />
    <xacro:link_hand name="right_hand_link" hand_l="${hand_l}" hand_w="${hand_w}" hand_h="${hand_h}" />

    <link name="neck_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${neck_rad}" length="${neck_len}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${neck_rad}" length="${neck_len}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="1" ixy="0.0" ixz="0.0" iyy="1" iyz="0.0" izz="1"/>
        </inertial>
    </link>

    <xacro:link_ocular name="left_ocular_link" ocular_rad="${ocular_rad}" ocular_len="${ocular_len}" />
    <xacro:link_eye name="left_eye_link" ocular_rad="${ocular_rad}" />
    
    <xacro:link_ocular name="right_ocular_link" ocular_rad="${ocular_rad}" ocular_len="${ocular_len}" />
    <xacro:link_eye name="right_eye_link" ocular_rad="${ocular_rad}" />

    <!-- * * * Joint Definitions * * * -->
    
    <xacro:joint_wheel name="wheel_1_left_joint" child="wheel_1_left" origin_xyz="${wheel_rad*2} ${base_side/2 + wheel_len/2} 0" />
    <xacro:joint_wheel_line name="wheel_1_left_line_joint" parent="wheel_1_left" child="wheel_1_left_line" origin_xyz="0 ${wheel_len/2} 0" />
    
    <xacro:joint_wheel name="wheel_2_left_joint" child="wheel_2_left" origin_xyz="0 ${base_side/2 + wheel_len/2} 0" />
    <xacro:joint_wheel_line name="wheel_2_left_line_joint" parent="wheel_2_left" child="wheel_2_left_line" origin_xyz="0 ${wheel_len/2} 0" />
    
    <xacro:joint_wheel name="wheel_3_left_joint" child="wheel_3_left" origin_xyz="-${wheel_rad*2} ${base_side/2 + wheel_len/2} 0" />
    <xacro:joint_wheel_line name="wheel_3_left_line_joint" parent="wheel_3_left" child="wheel_3_left_line" origin_xyz="0 ${wheel_len/2} 0" />
    
    <xacro:joint_wheel name="wheel_1_right_joint" child="wheel_1_right" origin_xyz="${wheel_rad*2} -${base_side/2 + wheel_len/2} 0" />
    <xacro:joint_wheel_line name="wheel_1_right_line_joint" parent="wheel_1_right" child="wheel_1_right_line" origin_xyz="0 -${wheel_len/2} 0" />
    
    <xacro:joint_wheel name="wheel_2_right_joint" child="wheel_2_right" origin_xyz="0 -${base_side/2 + wheel_len/2} 0" />
    <xacro:joint_wheel_line name="wheel_2_right_line_joint" parent="wheel_2_right" child="wheel_2_right_line" origin_xyz="0 -${wheel_len/2} 0" />
    
    <xacro:joint_wheel name="wheel_3_right_joint" child="wheel_3_right" origin_xyz="-${wheel_rad*2} -${base_side/2 + wheel_len/2} 0" />
    <xacro:joint_wheel_line name="wheel_3_right_line_joint" parent="wheel_3_right" child="wheel_3_right_line" origin_xyz="0 -${wheel_len/2} 0" />
    
    <xacro:joint_shoulder name="left_shoulder_joint" child="left_shoulder_link" origin_xyz="0 ${base_side/2 + shoulder_w/2} ${arm_pos}" />
    <xacro:joint_shoulder_forward name="left_shoulder_forward_joint" parent="left_shoulder_link" child="left_shoulder_forward_link" origin_xyz="0 ${shoulder_w/2 + shoulder_forward_w/2} 0" />
    <xacro:joint_upper_arm name="left_upper_arm_joint" parent="left_shoulder_forward_link" child="left_upper_arm_link" origin_xyz="${shoulder_forward_h/2 + upper_arm_len/2} 0 0" />
    <xacro:joint_arm_center name="left_center_joint" parent="left_upper_arm_link" child="left_center_link" origin_xyz="0 0 ${arm_center_h/2 + upper_arm_len/2}" />
    <xacro:joint_hand name="left_hand_joint" parent="left_center_link" child="left_hand_link" origin_xyz="0 0 ${arm_center_h/2 + hand_h/2}" />
    
    <xacro:joint_shoulder name="right_shoulder_joint" child="right_shoulder_link" origin_xyz="0 -${base_side/2 + shoulder_w/2} ${arm_pos}" />
    <xacro:joint_shoulder_forward name="right_shoulder_forward_joint" parent="right_shoulder_link" child="right_shoulder_forward_link" origin_xyz="0 -${shoulder_w/2 + shoulder_forward_w/2} 0" />
    <xacro:joint_upper_arm name="right_upper_arm_joint" parent="right_shoulder_forward_link" child="right_upper_arm_link" origin_xyz="${shoulder_forward_h/2 + upper_arm_len/2} 0 0" />
    <xacro:joint_arm_center name="right_center_joint" parent="right_upper_arm_link" child="right_center_link" origin_xyz="0 0 ${arm_center_h/2 + upper_arm_len/2}" />
    <xacro:joint_hand name="right_hand_joint" parent="right_center_link" child="right_hand_link" origin_xyz="0 0 ${arm_center_h/2 + hand_h/2}" />

     <joint name="neck_joint" type="revolute">
        <parent link="base_link"/>
        <child link="neck_link"/>
        <origin xyz="0 0 ${base_side + neck_len/2}" rpy="0 0 0"/>
        <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
        <joint_properties damping="1.0" friction="1.0" />
        <axis xyz="0 0 1"/>
    </joint>

    <xacro:joint_ocular name="left_ocular_joint" child="left_ocular_link" origin_xyz="0 ${ocular_rad*7/8} ${neck_len - ocular_rad/2}" />
    <xacro:joint_eye name="left_eye_joint" parent="left_ocular_link" child="left_eye_link" origin_xyz="${neck_len/2} 0 0" />
    
    <xacro:joint_ocular name="right_ocular_joint" child="right_ocular_link" origin_xyz="0 -${ocular_rad*7/8} ${neck_len - ocular_rad/2}" />
    <xacro:joint_eye name="right_eye_joint" parent="right_ocular_link" child="right_eye_link" origin_xyz="${neck_len/2} 0 0" />

    <!-- * * * Transmission * * * -->

    <joint_transmission_macro joint_name="wheel_1_left_joint"/>
    <joint_transmission_macro joint_name="wheel_2_left_joint"/>
    <joint_transmission_macro joint_name="wheel_3_left_joint"/>
    
    <joint_transmission_macro joint_name="wheel_1_right_joint"/>
    <joint_transmission_macro joint_name="wheel_2_right_joint"/>
    <joint_transmission_macro joint_name="wheel_3_right_joint"/>
    
    <joint_transmission_macro joint_name="left_shoulder_forward_joint"/>
    <joint_transmission_macro joint_name="left_center_joint"/>
    
    <joint_transmission_macro joint_name="right_shoulder_forward_joint"/>
    <joint_transmission_macro joint_name="right_center_joint"/>
    
    <joint_transmission_macro joint_name="neck_joint"/>

    <!--  Robot navigation with keyboard  -->
    <gazebo>
        <plugin filename="libgazebo_ros_diff_drive.so" name="differential_drive_controller">
            <alwaysOn>true</alwaysOn>
            <updateRate>20</updateRate>
            <leftJoint>wheel_2_left_joint</leftJoint>
            <rightJoint>wheel_2_right_joint</rightJoint>
            <wheelSeparation>${base_side}</wheelSeparation>
            <wheelDiameter>${wheel_rad*2}</wheelDiameter>
            <torque>2</torque>
            <commandTopic>cmd_vel</commandTopic>
            <odometryTopic>odom</odometryTopic>
            <odometryFrame>odom</odometryFrame>
            <robotBaseFrame>base_link</robotBaseFrame>
        </plugin>
    </gazebo>
</robot>